Pages/CourseStudents.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using school.Data;
using school.services;

namespace MyApp.Namespace
{
    public class CourseStudentsModel : PageModel
    {
        private StudentService _service { get; set; }
        public CourseStudentsModel(StudentService service)
        {
            this._service = service;
        }

        [BindProperty(SupportsGet = true)]
        public int courseId { get; set; }
        public List<Student> students { get; set; }
        public Course courseInfo { get; set; }
        public void OnGet()
        {
            students = _service.getStudentForCourse(courseId);
            courseInfo = _service.getCourseById(courseId);
        }
    }
}

Pages/Courses.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using school.Data;
using school.services;

namespace MyApp.Namespace
{
    public class CoursesModel : PageModel
    {
        public StudentService _service { get; set; }
        public CoursesModel(StudentService service){
            this._service = service;
        }
        public List<Course> courses { get; set; }
        public void OnGet()
        {
            courses = _service.getAllCourses();
        }
    }
}

Pages/CreateStudent.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class CreateStudentModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace school.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace school.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/NewCourse.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using school.Pages.Bind;
using school.services;

namespace MyApp.Namespace
{
    public class NewCourseModel : PageModel
    {
        private readonly StudentService _service;
        public NewCourseModel(StudentService service)
        {
            this._service = service;
        }

        [BindProperty(SupportsGet = true)]
        public CourseBinding Input { get; set; }
        public void OnGet()
        {
        }

        public void OnPostCreate(){
            if(ModelState.IsValid){
                _service.createCourse(Input);
            }else{
                ModelState.AddModelError(string.Empty, "An error occured while adding a new course");
            }
            
        }
    }
}

Pages/NewStudents.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using school.Data;
using school.Pages.Bind;
using school.services;

namespace MyApp.Namespace
{
    public class NewStudentsModel : PageModel
    {
        private readonly StudentService _service;
        public NewStudentsModel(StudentService service)
        {
            this._service = service;
        }
        [BindProperty(SupportsGet = true)]
        public int studentId { get; set; }
        [BindProperty]
        public Student st { get; set; }
        [BindProperty]
        public StudentBinding Input { get; set; }
        public List<SelectListItem> courses { get; set; } = new List<SelectListItem>{
            new SelectListItem { Value="", Text="Choose courses", Disabled=true }
        };
        public List<SelectListItem> nationalities { get; set; } = new List<SelectListItem>{
            new SelectListItem { Value="", Text="Choose Nationality", Disabled=true}
        };


        public void OnGet()
        {
            courses = _service.getAllCourses(courses);
            nationalities = _service.getAllNationalities(nationalities);
        }

        public IActionResult OnGetEdit(){
            st = _service.GetStudent(studentId, courses ,nationalities);
            return Page();
        }

        public IActionResult OnPostCreate(){
            _service.createStudent(Input);
            return RedirectToPage("/Students");
        }

        public IActionResult OnPostUpdate(){
            _service.Edit(studentId, Input);
            return RedirectToPage("/Students");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace school.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Students.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using school.Data;
using school.services;

namespace MyApp.Namespace
{
    public class StudentsModel : PageModel
    {  
        private readonly StudentService _service;
        public StudentsModel(StudentService service)
        {
            this._service = service;
        }
        [BindProperty(SupportsGet = true)]
        public int studentId { get; set; }

        public List<Student> students {get; set; }

        public void OnGet()
        {
            students = _service.getAllStudents();            
        }

        public void OnPostDelete()
        {
            _service.deleteStudent(studentId);
            students = _service.getAllStudents();
        }
    }
}

Pages/CourseStudents.cshtml
@page "{courseId:int}"
@model MyApp.Namespace.CourseStudentsModel
@{
    ViewData["Title"] = @Model.courseInfo.Name+" Students";
}

<h1>All Students Registered for @Model.courseInfo.Name</h1>

<table class="table">
    <tr>
        <td>#</td>
        <td>Name</td>
        <td>Email</td>
        <td>Age</td>
        <td>Gender</td>
        <td>Nationality</td>
    </tr>
    @foreach (var student in Model.students)
    {
        <tr>
            <td>@student.StudentId</td>
            <td>@student.Name</td>
            <td>@student.Email</td>
            <td>@student.Age</td>
            <td>@student.Gender</td>
            <td>@student.Nationality.Name</td>
        </tr>
    }
</table>

Pages/Courses.cshtml
@page
@model MyApp.Namespace.CoursesModel
@{
    ViewData["Title"] = "All Courses";
}


<h1>All Courses</h1>

<table class="table">
    <tr>
        <td>#</td>
        <td>Name</td>
        <td>Action</td>
        <td></td>
    </tr>
    @foreach (var course in Model.courses)
    {
        <tr>
            <td>@course.CourseId</td>
            <td>@course.Name</td>
            <td><a asp-page="/CourseStudents" asp-route-courseId="@course.CourseId" class="btnAction">show students registered</a></td>
        </tr>
    }
</table>

Pages/CreateStudent.cshtml
@page
@model MyApp.Namespace.CreateStudentModel
@{
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/NewCourse.cshtml
@page "{handler?}"
@model MyApp.Namespace.NewCourseModel
@{
    ViewData["Title"] = "Add Course";
}

<h2>Add Course</h2>

<form method="POST">
    <div class="form-group">
        <label asp-for="Input.courseName"></label>
        <input class="form-control" asp-for="Input.courseName">
        <span style="color:red;" asp-validation-for="Input.courseName"></span>
    </div><br><br>

    
    <button asp-page-handler="Create" type="submit" class="btn btn-primary">Add Course</button>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
</form>

Pages/NewStudents.cshtml
@page "{handler?}/{studentId:int?}"
@model MyApp.Namespace.NewStudentsModel
@{
    @if(Model.st != null){
        ViewData["Title"] = "Edit Student";
    } else {
        ViewData["Title"] = "Add Student";
    }
    
}

@if(Model.st != null){
    <h2>Edit Student</h2>
} else {
    <h2>Add New Student</h2>
}


<form method="POST">
    <div class="form-group">
        <label asp-for="Input.studentName"></label>
        <input class="form-control" asp-for="Input.studentName" value="@Model.st?.Name">
    </div><br>

    <div class="form-group">
        <label asp-for="Input.studentEmail"></label>
        <input class="form-control" asp-for="Input.studentEmail" value="@Model.st?.Email">
    </div><br>

    <div class="form-group">
        <label asp-for="Input.confirmEmail"></label>
        <input class="form-control" asp-for="Input.confirmEmail" value="@Model.st?.Email">
    </div><br>

    <div class="form-group">
        <label asp-for="Input.studentAge"></label>
        <input class="form-control" asp-for="Input.studentAge" value="@Model.st?.Age">
    </div><br>

    @if(Model.st != null){
        @if(Model.st.Gender == "male"){
            <label class="form-check-label" asp-for="Input.studentGender"></label>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="Input.studentGender" value="male" checked>
                <label for="">Male</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="Input.studentGender" value="female">
                <label for="">Female</label>
            </div><br>
        } else {
            <label class="form-check-label" asp-for="Input.studentGender"></label>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="Input.studentGender" value="male">
                <label for="">Male</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="Input.studentGender" value="female" checked>
                <label for="">Female</label>
            </div><br>
        }
    } else {
        <label class="form-check-label" asp-for="Input.studentGender"></label>
        <div class="form-check">
            <input class="form-check-input" type="radio" asp-for="Input.studentGender" value="male">
            <label for="">Male</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" asp-for="Input.studentGender" value="female">
            <label for="">Female</label>
        </div><br>
    }
    

    <div class="form-group">
        <label asp-for="Input.CoursesIds"></label>
        <select class="form-control" asp-items="Model.courses" asp-for="Input.CoursesIds" multiple></select>
    </div><br>

    <div class="form-group">
        <label asp-for="Input.NationalityId"></label>
        <select class="form-control" asp-items="Model.nationalities" asp-for="Input.NationalityId" ></select>
    </div><br><br>

    @if(Model.st != null){
        <button asp-page-handler="Update" asp-route-studentId="@Model.st.StudentId" type="submit" class="btn btn-primary">Update Student</button>
    } else {
        <button asp-page-handler="Create" type="submit" class="btn btn-primary">Add Student</button>
    }
    
</form>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - school</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/school.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">school</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/NewStudents">Add Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/NewCourse">Add Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Students">All Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Courses">All Courses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - school - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/Students.cshtml
@page "{handler?}/{studentId:int?}"
@model MyApp.Namespace.StudentsModel
@{
    ViewData["Title"] = "All Students";
}

<h1>All Students</h1>

<table class="table">
    <tr>
        <td>#</td>
        <td>Name</td>
        <td>Email</td>
        <td>Age</td>
        <td>Gender</td>
        <td>Courses</td>
        <td>Nationality</td>
        <td>Action</td>
        <td></td>
    </tr>
    @foreach (var student in Model.students)
    {
        <tr>
            <td>@student.StudentId</td>
            <td>@student.Name</td>
            <td>@student.Email</td>
            <td>@student.Age</td>
            <td>@student.Gender</td>
            <td>
                @if (student.Courses.Count() == 0)
                {
                    <pre>No courses selected</pre>
                }
                @foreach (var course in student.Courses)
                {
                    <p>@course.Name</p>
                }
            </td>
            <td>@student.Nationality.Name</td>
            <td style="display: flex; gap: 8px;">
                <form method="POST">
                    <button asp-page-handler="Delete" asp-route-studentId="@student.StudentId" class="btnAction">Delete</button>
                </form>
                <a asp-page="/NewStudents" asp-page-handler="Edit" asp-route-studentId="@student.StudentId" class="btnAction">Edit</a>
            </td>
        </tr>
    }
</table>